namespace Cpp2IL.Core.ISIL;

public enum IsilMnemonic
{
    Move,
    Load,
    Store,
    CompareTempMove,
    LoadAddress,
    Call,
    CallNoReturn,
    Exchange,
    Add,
    Subtract,
    Multiply,
    Divide,
    ShiftLeft,
    ShiftRight,
    And,
    Or,
    Xor,
    Not,
    Neg,
    Compare,
    ShiftStack,
    Push,
    Pop,
    Return,
    Goto,
    JumpIfEqual,
    JumpIfNotEqual,
    JumpIfGreater,
    JumpIfGreaterOrEqual,
    JumpIfLess,
    JumpIfLessOrEqual,
    JumpIfSign,
    JumpIfNotSign,
    SignExtend,
    Interrupt,
    Nop,
    NotImplemented,
    Invalid,
    VirtualCall,
    RGCTXCall,
    VTableCall,
    AssignIfNotEqual,
    AssignIfEqual,
    AssignIfLessThan,
    AssignIfGreaterOrEqual, //>=
    AssignIfGreaterThan, //>
    AssignIfLessOrEqual, //<=
    Cast2BaseType,//cat to base type
    VectorElementLoad, //Vector element access
    VectorElementStore, //Vector element store
    FABD,
    FMOV,
    FSQRT, //Math operations like FSQRT, FMIN, etc.
    FMIN,
    FMINNM,
    FMAX,
    FNMUL,
    FABS,
    MOVK,
    MADD,
    BFM,
    SIMDMath,
    ExtractVector,
    REV64,
    UZP1,
    UZP2,
    UBFX,
    BFXIL,
    LoadImmToVector,
    LoadRegisterToVector,
    Ceiling,
    Floor,
    LSR,
    ASR,
    LSL,
    BFI,
    SDIV,
    UDIV,
    StackFrame,
}
